SET DEFINE OFF;
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 11, 'Periodo presentación solicitudes', 'Seleccionar convocatoria');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 12, 'Periodo presentación solicitudes', 'Cumplimentar solicitud');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 13, 'Periodo presentación solicitudes', 'Pago de tasa');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 14, 'Periodo presentación solicitudes', 'Cerrada por caducidad');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 15, 'Periodo presentación solicitudes', 'Suspendida a espera de registro');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 1, 16, 'Periodo presentación solicitudes', 'Solicitud registrada');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 2, 21, '1er. Periodo revisión de solicitudes', 'Pendiente revisar solicitud');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 2, 22, '1er. Periodo revisión de solicitudes', 'Admitida provisional');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 2, 23, '1er. Periodo revisión de solicitudes', 'Excluida provisional');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 2, 24, '1er. Periodo revisión de solicitudes', 'Cerrada por excluida (1er periodo)');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 3, 31, 'Periodo de recepción de subsanaciones', 'Aportar documentación');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 3, 32, 'Periodo de recepción de subsanaciones', 'Documentación aportada');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 4, 41, '2do. Periodo revisión de solicitudes', 'Pendiente revisar subsanacion');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 4, 42, '2do. Periodo revisión de solicitudes', 'Admitida definitiva');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 4, 43, '2do. Periodo revisión de solicitudes', 'Excluida definitiva');
Insert into ETAPASITUACION
   (PROCEDIMIENTO, CODETAPA, CODSITUACION, DESCETAPA, DESCSITUACION)
 Values
   ('02-23', 4, 44, '2do. Periodo revisión de solicitudes', 'Cerrada por excluida (2do periodo)');
COMMIT;
